// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/niluwats/invoice-marketplace/internal/domain"
	errors "github.com/niluwats/invoice-marketplace/pkg/errors"

	mock "github.com/stretchr/testify/mock"
)

// InvestorRepository is an autogenerated mock type for the InvestorRepository type
type InvestorRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *InvestorRepository) FindAll() ([]domain.Investor, *errors.AppError) {
	ret := _m.Called()

	var r0 []domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func() ([]domain.Investor, *errors.AppError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Investor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func() *errors.AppError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: email
func (_m *InvestorRepository) FindByEmail(email string) (*domain.Investor, *errors.AppError) {
	ret := _m.Called(email)

	var r0 *domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(string) (*domain.Investor, *errors.AppError)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Investor); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *errors.AppError); ok {
		r1 = rf(email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *InvestorRepository) FindById(id int) (*domain.Investor, *errors.AppError) {
	ret := _m.Called(id)

	var r0 *domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(int) (*domain.Investor, *errors.AppError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Investor); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *errors.AppError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: investor
func (_m *InvestorRepository) Save(investor domain.Investor) *errors.AppError {
	ret := _m.Called(investor)

	var r0 *errors.AppError
	if rf, ok := ret.Get(0).(func(domain.Investor) *errors.AppError); ok {
		r0 = rf(investor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.AppError)
		}
	}

	return r0
}

// NewInvestorRepository creates a new instance of InvestorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvestorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvestorRepository {
	mock := &InvestorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
