// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/niluwats/invoice-marketplace/internal/domain"
	errors "github.com/niluwats/invoice-marketplace/pkg/errors"

	mock "github.com/stretchr/testify/mock"
)

// InvestorRepository is an autogenerated mock type for the InvestorRepository type
type InvestorRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *InvestorRepository) FindAll(ctx *context.Context) ([]domain.Investor, *errors.AppError) {
	ret := _m.Called(ctx)

	var r0 []domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context) ([]domain.Investor, *errors.AppError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*context.Context) []domain.Investor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context) *errors.AppError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *InvestorRepository) FindByEmail(ctx *context.Context, email string) (*domain.Investor, *errors.AppError) {
	ret := _m.Called(ctx, email)

	var r0 *domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, string) (*domain.Investor, *errors.AppError)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, string) *domain.Investor); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, string) *errors.AppError); ok {
		r1 = rf(ctx, email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, id
func (_m *InvestorRepository) FindById(ctx *context.Context, id int) (*domain.Investor, *errors.AppError) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Investor
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, int) (*domain.Investor, *errors.AppError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, int) *domain.Investor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investor)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, int) *errors.AppError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, investor
func (_m *InvestorRepository) Save(ctx *context.Context, investor domain.Investor) *errors.AppError {
	ret := _m.Called(ctx, investor)

	var r0 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, domain.Investor) *errors.AppError); ok {
		r0 = rf(ctx, investor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.AppError)
		}
	}

	return r0
}

// NewInvestorRepository creates a new instance of InvestorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvestorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvestorRepository {
	mock := &InvestorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
