// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/niluwats/invoice-marketplace/internal/domain"
	errors "github.com/niluwats/invoice-marketplace/pkg/errors"

	mock "github.com/stretchr/testify/mock"
)

// InvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type InvoiceRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *InvoiceRepository) FindAll(ctx *context.Context) ([]domain.Invoice, *errors.AppError) {
	ret := _m.Called(ctx)

	var r0 []domain.Invoice
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context) ([]domain.Invoice, *errors.AppError)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*context.Context) []domain.Invoice); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context) *errors.AppError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, id
func (_m *InvoiceRepository) FindById(ctx *context.Context, id int) (*domain.Invoice, *errors.AppError) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Invoice
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, int) (*domain.Invoice, *errors.AppError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, int) *domain.Invoice); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, int) *errors.AppError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// FindIfExistsByNo provides a mock function with given fields: ctx, invoiceNo
func (_m *InvoiceRepository) FindIfExistsByNo(ctx *context.Context, invoiceNo string) bool {
	ret := _m.Called(ctx, invoiceNo)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*context.Context, string) bool); ok {
		r0 = rf(ctx, invoiceNo)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindTotalInvestment provides a mock function with given fields: ctx, id
func (_m *InvoiceRepository) FindTotalInvestment(ctx *context.Context, id int) (float64, *errors.AppError) {
	ret := _m.Called(ctx, id)

	var r0 float64
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, int) (float64, *errors.AppError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, int) float64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(*context.Context, int) *errors.AppError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, invoice
func (_m *InvoiceRepository) Insert(ctx *context.Context, invoice domain.Invoice) (*domain.Invoice, *errors.AppError) {
	ret := _m.Called(ctx, invoice)

	var r0 *domain.Invoice
	var r1 *errors.AppError
	if rf, ok := ret.Get(0).(func(*context.Context, domain.Invoice) (*domain.Invoice, *errors.AppError)); ok {
		return rf(ctx, invoice)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, domain.Invoice) *domain.Invoice); ok {
		r0 = rf(ctx, invoice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, domain.Invoice) *errors.AppError); ok {
		r1 = rf(ctx, invoice)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}

	return r0, r1
}

// NewInvoiceRepository creates a new instance of InvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvoiceRepository {
	mock := &InvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
